--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by saber.
--- DateTime: 2022/7/6 17:38
---

print("lua begin")
------------ array_test ---------------
local t1 = { "张三", "李四", "abc", "1234" }
array_test(t1)
-------------- map_test -------------
local t2 = { a = "张三", b = "李四", c = "abc", d = "1234" }
map_test(t2)

--------------- checkType_test ------------
checkType_test("abc", true)

------------- simple_test --------------
local score = simple_test("张三", 12)
print("score = ", score)
score = nil

------------- ret_test --------------
local ret1, ret2 = ret_test()
print("ret1 = ", ret1, "  ret2 = ", ret2)
ret1 = nil
ret2 = nil

------------- ret_table_test --------------
local t3 = ret_table_test()
print("t3 = ", t3)
for i, v in pairs(t3) do
    print(i .. " => " .. v)
end

t3 = nil

------------- getLuaVar_test --------------
g_var1 = 13.4

----------- getLuaVar_table_test -------------
g_t1 = {
    name = "王五", age = 22,
}

g_t2 = {
    { name = "张三", age = 21 },
    { name = "王五", age = 22 },
    { name = "李明", age = 12 },
}

---------- set2LuaVar_test -------------
print(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>  lua get c++ global var")
print("c++ g_name = " .. g_name)

----------- setLuaVar_table_test ------------
print(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>  lua get c++ global table var")
print("g_varTable ==> ", g_varTable)
print("g_varTable name ==> " .. g_varTable["name"])

----------- callLuaFunc_simple -------------

function luaSimpleFunc1()
    -- 测试错误用
    --function luaSimpleFunc()
    print("c++ call lua func simple")
end

---------------- callLuaFunc_params_ret -------------------
--function luaParamsAndRetFunc1(name, age, t)  -- 测试错误用
function luaParamsAndRetFunc(name, age, t)
    --function luaSimpleFunc()
    print("c++ call lua params and ret func")
    print("name = ", name, "  age = ", age, "  t = ", t, "  t.score = ", t.score)
    local retTable = { name = "saber", age = 20 }
    return "this is a lua params_return func return", retTable
end

function fError(e)
    print("原始Error = ", e)
    return "这是自定义错误处理函数返回的错误，将覆盖原始返回的错误"
end
